active_postal_codes: 9355 9356 9987 9915 9613 9914 9912
facebook_url: 'https://www.facebook.com/Easy-Driving-585926995247444/'
twitter_url: 'https://twitter.com/EasyDrivingNL'
linkedin_url: 'https://www.linkedin.com/company/easy-drivingeu/about/'
car_locations:
  - address: Oude Merenweg 10, Meerstad
    lat: 53.226734
    long: 6.648060
  - address: Talingeneiland 15, Meerstad
    lat: 53.226371
    long: 6.651594
