active_postal_codes: 9355 9987 9915
facebook_url: https://www.facebook.com/Easy-Driving-585926995247444/
twitter_url: https://twitter.com/EasyDrivingNL
linkedin_url: https://www.linkedin.com/company/easy-drivingeu/about/
