# Everything you need to know about configuring the CMS can be found here:-
# https://www.netlifycms.org/docs/configuration-options/

backend:
  name: git-gateway # Netlify’s Git Gateway connects to Git provider’s API
  branch: master # Branch to update (master by default)

media_folder: "_site/dist/img/uploads" # Folder where user uploaded files should go

# publish_mode: editorial_workflow # Enable drafts

logo_url: https://pensive-edison-7425f6.netlify.com/dist/img/logo.svg

collections: # A list of collections the CMS should be able to edit
  # PAGES
  - name: "page"
    label: "Page"
    folder: "pages"
    sort: "title:asc"
    create: false
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden"}
      - {label: "Title", name: "title", widget: "hidden"}
      - {label: "Title tag (SEO)", name: "title_tag", widget: "string"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Name", name: "name", widget: "hidden"}
      - {label: "Hero Heading", name: "hero_heading", widget: "string", required: false}
      - {label: "Hero Subheading", name: "hero_subheading", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "hidden"}
