# Everything you need to know about configuring the CMS can be found here:-
# https://www.netlifycms.org/docs/configuration-options/

backend:
  name: git-gateway # Netlify’s Git Gateway connects to Git provider’s API
  branch: master # Branch to update (master by default)

media_folder: "_site/uploads" # Folder where user uploaded files should go
public_folder: "/uploads"

# publish_mode: editorial_workflow # Enable drafts

logo_url: https://pensive-edison-7425f6.netlify.com/dist/img/logo.svg

collections: # A list of collections the CMS should be able to edit
  # SETTINGS
  - name: "settings"
    label: "Instellingen"
    description: "Algemene site instellingen"
    delete: "false"
    editor:
      preview: true
    files:
      - name: 'general'
        label: 'Instellingen'
        file: "/_data/settings.yaml"
        fields:
          - {label: "Postcodes waarin EasyDriving beschikbaar is (spatie tussen de 4-cijferige postcodes)", name: "active_postal_codes", widget: "text"}
          - {label: "Facebook profile link", name: "facebook_url:", widget: "string"}
          - {label: "Twitter profile link", name: "twitter_url:", widget: "string"}
          - {label: "LinkedIn profile link", name: "linkedin_url:", widget: "string"}
      - name: "cars"
        label: "Auto's"
        file: "/_data/cars.yaml"
        create: true
        fields:
          - label: "Auto"
            name: "cars"
            widget: list
            fields:
              - { label: "Merk + model", name: "title", widget: "string" }
              - { label: "Foto", name: "image", widget: "image" }
              - { label: "Actieradius", name: "actieradius", widget: "string" }
              - { label: "Aantal zitplaatsen", name: "seats", widget: "string" }
              - { label: "Prijs per uur", name: "price_per_hour", widget: "string" }
              - { label: "Prijs per dag", name: "price_per_day", widget: "string" }
              - { label: "Prijs per km", name: "price_per_km", widget: "string" }

  # HOMEPAGE
  - name: "homepage"
    label: "Homepage"
    delete: "false"
    files:
      - name: "homepage"
        label: "Homepage"
        file: "/pages/index.html"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden"}
          - {label: "Title", name: "title", widget: "hidden"}
          - {label: "Title tag (SEO)", name: "title_tag", widget: "string"}
          - {label: "Description tag (SEO)", name: "description_tag", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "hidden"}
          - {label: "Body", name: "body", widget: "hidden"}
      - name: "hero"
        label: "Hero"
        file: "/_data/hero.yaml"
        fields:
          - {label: "Heading", name: "heading", widget: "string"}
          - {label: "Subheading", name: "subheading", widget: "string"}
          - {label: "Button Text", name: "button_text", widget: "string"}
      - name: "our_cars"
        label: "Onze auto's"
        file: "/_data/our_cars.yaml"
        fields:
          - {label: "Heading", name: "heading", widget: "string"}
          - {label: "Button text", name: "button_text", widget: "string"}
      - name: "usps"
        label: "USP's"
        file: "/_data/usps.yaml"
        fields:
          - {label: "USP 1 icon", name: "usps_1_image", widget: "image"}
          - {label: "USP 1 titel", name: "usps_1_heading", widget: "string"}
          - {label: "USP 1 text", name: "usps_1_text", widget: "markdown"}
          - {label: "USP 2 icon", name: "usps_2_image", widget: "image"}
          - {label: "USP 2 titel", name: "usps_2_heading", widget: "string"}
          - {label: "USP 2 text", name: "usps_2_text", widget: "markdown"}
          - {label: "USP 3 icon", name: "usps_3_image", widget: "image"}
          - {label: "USP 3 titel", name: "usps_3_heading", widget: "string"}
          - {label: "USP 3 text", name: "usps_3_text", widget: "markdown"}
          - {label: "USP button text", name: "usps_button_text", widget: "string"}
      - name: "app_banner"
        label: "App banner"
        file: "_data/app_banner.yaml"
        fields:
          - { label: "Tekst", name: "text", widget: "string" }
      - name: "how_it_works"
        label: "Hoe werkt het?"
        file: "_data/how_it_works.yaml"
        fields:
          - {label: "Heading", name: "heading", widget: "string"}
          - {label: "Title 1", name: "title1", widget: "string"}
          - {label: "Text 1", name: "text1", widget: "text"}
          - {label: "Title 2", name: "title2", widget: "string"}
          - {label: "Text 2", name: "text2", widget: "text"}
          - {label: "Title 3", name: "title3", widget: "string"}
          - {label: "Text 3", name: "text3", widget: "text"}
          - {label: "Title 4", name: "title4", widget: "string"}
          - {label: "Text 4", name: "text4", widget: "text"}
          - {label: "Button text", name: "button_text", widget: "string"}
      - name: "compare_costs_tool"
        label: "Kostenvergelijker tool"
        file: "_data/compare_costs.yaml"
        fields:
          - { name: "heading", label: "Heading", widget: "string" }
          - { name: "description", label: "Beschrijving", widget: "text" }
          - { name: "distance_label", label: "Afstand label", widget: "string" }
          - { name: "car1", label: "Auto 1 (in iegen bezit)", widget: "string" }
          - { name: "car2", label: "Auto 2 (via EasyDriving)", widget: "string" }
          - { name: "afschrijvingskosten_label", label: "Afschrijvingskosten label", widget: "string" }
          - { name: "verzekering_label", label: "Verzekering label", widget: "string" }
          - { name: "belasting_label", label: "Belasting label", widget: "string" }
          - { name: "onderhoud_label", label: "Onderhoud label", widget: "string" }
          - { name: "benzine_label", label: "Benzine label", widget: "string" }
          - { name: "subscription_label", label: "Lidmaatschap EasyDriving label", widget: "string" }
          - { name: "deelauto_label", label: "Kosten deelauto label", widget: "string" }
          - { name: "distance", label: "Initiële afstand", widget: "string" }
          - { name: "maximum", label: "Maximum aantal km per jaar", widget: "string" }
          - { name: "afschrijvingskosten", label: "Afschrijvingskosten per jaar", widget: "string" }
          - { name: "verzekering", label: "Verzekeringskosten per jaar", widget: "string" }
          - { name: "belasting", label: "Belasting per jaar", widget: "string" }
          - { name: "onderhoud", label: "Onderhoud kosten per jaar", widget: "string" }
          - { name: "benzineprijs", label: "Benzine literprijs", widget: "string" }
          - { name: "subscription_costs", label: "Kosten lidmaatschap EasyDriving (per jaar)", widget: "string" }
          - { name: "stroomkosten", label: "Stroomkosten (per km)", widget: "string" }
          - { name: "button_text", label: "Button tekst", widget: "string" }
      - name: "availability"
        label: "Availability"
        file: "_data/availability.yaml"
        fields:
          - { label: "Heading", name: "heading", widget: "string" }
          - { label: "Formulier vraag", name: "form_question", widget: "string" }
          - { label: "Formulier button text", name: "form_submit_text", widget: "string" }
          - { label: "Geen beschikbaarheid text", name: "negative_result_text", widget: "markdown" }
          - { label: "E-mail adres", name: "email_address", widget: "string" }
          - { label: "Geen beschikbaarheid button text", name: "negative_form_button_text", widget: "string" }
          - { label: "Wel beschikbaarheid text", name: "positive_result_text", widget: "markdown" }
  # OTHER PAGES
  - name: "other_pages"
    label: "Overige pagina's"
    delete: "false"
    editor:
      preview: true
    files:
      - name: 'privacy'
        label: "Privacy"
        file: "pages/privacy.html"
        fields:
          - { label: "Layout", name: "layout", widget: "hidden" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Title tag (SEO)", name: "title_tag", widget: "string" }
          - { label: "Description tag (SEO)", name: "description_tag", widget: "string" }
          - { label: "Permalink", name: "permalink", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - name: 'voorwaarden'
        label: "Voorwaarden"
        file: "pages/voorwaarden.html"
        fields:
          - { label: "Layout", name: "layout", widget: "hidden" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Title tag (SEO)", name: "title_tag", widget: "string" }
          - { label: "Description tag (SEO)", name: "description_tag", widget: "string" }
          - { label: "Permalink", name: "permalink", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
  # NEWS
  - name: "news"
    label: "Nieuws"
    folder: "_posts"
    sort: "date:desc"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post" }
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Datum", name: "friendly_date", widget: "string" }
      - { label: "URL", name: "permalink", widget: "string" }
      - { label: "Categorie", name: "category", widget: "string" }
      - { label: "Inhoud", name: "body", widget: "markdown" }
  # FOOTER
  - name: "footer"
    label: "Footer"
    delete: "false"
    files:
      - name: 'footer'
        label: "Footer"
        file: "/_data/footer.yaml"
        fields:
          - { label: "Infotekst", name: "company_description", widget: "markdown" }
          - { label: "Links heading", name: "links_heading", widget: "string" }
          - { label: "Contact heading", name: "contact_heading", widget: "string" }
          - { label: "Adres", name: "company_address", widget: "markdown" }
          - { label: "Copyright notice", name: "copyright_notice", widget: "string" }
          - { label: "Nieuwsbrief heading", name: "newsletter_heading", widget: "string" }
          - { label: "Nieuwsbrief beschrijving", name: "newsletter_description", widget: "string" }
          - { label: "Nieuwsbrief text in inputveld (placeholder)", name: "newsletter_input_placeholder", widget: "string" }
          - { label: "Nieuwsbrief text op submit knop", name: "newsletter_submit_text", widget: "string" }
