# Everything you need to know about configuring the CMS can be found here:-
# https://www.netlifycms.org/docs/configuration-options/

backend:
  name: git-gateway # Netlify’s Git Gateway connects to Git provider’s API
  branch: master # Branch to update (master by default)

media_folder: "_site/uploads" # Folder where user uploaded files should go
public_folder: "/uploads"

# publish_mode: editorial_workflow # Enable drafts

logo_url: https://pensive-edison-7425f6.netlify.com/dist/img/logo.svg

collections: # A list of collections the CMS should be able to edit
  # SETTINGS
  - name: "settings"
    label: "Instellingen"
    description: "Algemene site instellingen"
    delete: "false"
    editor:
      preview: false
    files:
      - name: 'general'
        label: 'Instellingen'
        file: "/_data/settings.yaml"
        fields:
          - {label: "Postcodes waarin EasyDriving beschikbaar is", name: "active_postal_codes", widget: "text"}
  # FOOTER
  - name: "footer"
    label: "Footer"
    delete: "false"
    files:
      - name: 'footer'
        label: "Footer"
        file: "/_data/footer.yaml"
        fields:
          - { label: "Infotekst", name: "company_description", widget: "markdown" }
          - { label: "Links heading", name: "links_heading", widget: "string" }
          - { label: "Contact heading", name: "contact_heading", widget: "string" }
          - { label: "Adres", name: "company_address", widget: "markdown" }
          - { label: "Copyright notice", name: "copyright_notice", widget: "string" }
  # HOMEPAGE
  - name: "homepage"
    label: "Homepage"
    files:
      - name: "homepage"
        label: "Homepage"
        file: "/pages/index.html"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden"}
          - {label: "Title", name: "title", widget: "hidden"}
          - {label: "Title tag (SEO)", name: "title_tag", widget: "string"}
          - {label: "Permalink", name: "permalink", widget: "hidden"}
          - {label: "Body", name: "body", widget: "hidden"}
      - name: "hero"
        label: "Hero"
        file: "/_data/hero.yaml"
        fields:
          - {label: "Heading", name: "heading", widget: "string"}
          - {label: "Subheading", name: "subheading", widget: "string"}
          - {label: "Button Text", name: "button_text", widget: "string"}
      - name: "our_cars"
        label: "Onze auto's"
        file: "/_data/our_cars.yaml"
        fields:
          - {label: "Heading", name: "heading", widget: "string"}
          - {label: "Auto 1 - Foto", name: "car1_image", widget: "image"}
          - {label: "Auto 1 - Titel", name: "car1_title", widget: "string"}
          - {label: "Auto 1 - Beschrijving", name: "car1_description", widget: "string"}
          - {label: "Auto 2 - Foto", name: "car2_image", widget: "image"}
          - {label: "Auto 2 - Titel", name: "car2_title", widget: "string"}
          - {label: "Auto 2 - Beschrijving", name: "car2_description", widget: "string"}
          - {label: "Auto 3 - Foto", name: "car3_image", widget: "image"}
          - {label: "Auto 3 - Titel", name: "car3_title", widget: "string"}
          - {label: "Auto 3 - Beschrijving", name: "car3_description", widget: "string"}
          - {label: "Auto 4 - Foto", name: "car4_image", widget: "image"}
          - {label: "Auto 4 - Titel", name: "car4_title", widget: "string"}
          - {label: "Auto 4 - Beschrijving", name: "car4_description", widget: "string"}
          - {label: "Auto 5 - Foto", name: "car5_image", widget: "image"}
          - {label: "Auto 5 - Titel", name: "car5_title", widget: "string"}
          - {label: "Auto 5 - Beschrijving", name: "car5_description", widget: "string"}
          - {label: "Button text", name: "button_text", widget: "string"}
      - name: "usps"
        label: "USP's"
        file: "/_data/usps.yaml"
        fields:
          - {label: "USP 1 icon", name: "usps_1_image", widget: "image"}
          - {label: "USP 1 titel", name: "usps_1_heading", widget: "string"}
          - {label: "USP 1 text", name: "usps_1_text", widget: "markdown"}
          - {label: "USP 2 icon", name: "usps_2_image", widget: "image"}
          - {label: "USP 2 titel", name: "usps_2_heading", widget: "string"}
          - {label: "USP 2 text", name: "usps_2_text", widget: "markdown"}
          - {label: "USP button text", name: "usps_button_text", widget: "string"}
      - name: "how_it_works"
        label: "Hoe werkt het?"
        file: "_data/how_it_works.yaml"
        fields:
          - {label: "Heading", name: "heading", widget: "string"}
          - {label: "Title 1", name: "title1", widget: "string"}
          - {label: "Text 1", name: "text1", widget: "text"}
          - {label: "Title 2", name: "title2", widget: "string"}
          - {label: "Text 2", name: "text2", widget: "text"}
          - {label: "Title 3", name: "title3", widget: "string"}
          - {label: "Text 3", name: "text3", widget: "text"}
          - {label: "Title 4", name: "title4", widget: "string"}
          - {label: "Text 4", name: "text4", widget: "text"}
          - {label: "Button text", name: "button_text", widget: "string"}
      - name: "availability"
        label: "Availability"
        file: "_data/availability.yaml"
        fields:
          - { label: "Heading", name: "heading", widget: "string" }
          - { label: "Formulier vraag", name: "form_question", widget: "string" }
          - { label: "Formulier button text", name: "form_submit_text", widget: "string" }
          - { label: "Geen beschikbaarheid text", name: "negative_result_text", widget: "markdown" }
          - { label: "E-mail adres", name: "email_address", widget: "string" }
          - { label: "Geen beschikbaarheid button text", name: "negative_form_button_text", widget: "string" }
          - { label: "Wel beschikbaarheid text", name: "positive_result_text", widget: "markdown" }
